# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/c_addsub_2_2/c_addsub_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_2 || ORIG_REF_NAME==c_addsub_2} -quiet] -quiet
