# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/HP/Desktop/MSc.-CNN-Acceleration-on-FPGA-/RTL Inference Model/Mobilenetv1 Lite.srcs/sources_1/DenseWeights/DenseWeights/DenseWeights.xci
# IP: The module: 'DenseWeights' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/MSc.-CNN-Acceleration-on-FPGA-/RTL Inference Model/Mobilenetv1 Lite.srcs/sources_1/DenseWeights/DenseWeights/DenseWeights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseWeights'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/HP/Desktop/MSc.-CNN-Acceleration-on-FPGA-/RTL Inference Model/Mobilenetv1 Lite.srcs/sources_1/DenseWeights/DenseWeights/DenseWeights.xci
# IP: The module: 'DenseWeights' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/MSc.-CNN-Acceleration-on-FPGA-/RTL Inference Model/Mobilenetv1 Lite.srcs/sources_1/DenseWeights/DenseWeights/DenseWeights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DenseWeights'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
